language: go

go:
  - 1.5.1

# whitelist
branches:
  only:
    - master
    - stable
    - release

install:
  - ./install-dependencies.sh
script: 
  - go test CodeCollaborate.go
  - go build CodeCollaborate.go